"""some message

Revision ID: b204ef3aecfd
Revises: aafb3209aa64
Create Date: 2025-10-21 17:45:36.789363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b204ef3aecfd'
down_revision: Union[str, Sequence[str], None] = 'aafb3209aa64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_conversation_active', 'sessions', ['conversation_id', 'is_active'], unique=False)
    op.add_column('conversations', sa.Column('channel', sa.String(length=32), server_default='whatsapp', nullable=False))
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.drop_column('conversations', 'title')
    op.add_column('messages', sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('messages', sa.Column('channel_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('message_type', sa.String(length=32), server_default='text', nullable=False))
    op.add_column('messages', sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', name='delivery_status'), server_default='queued', nullable=False))
    op.add_column('messages', sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index('ix_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_messages_status', 'messages', ['status'], unique=False)
    op.create_unique_constraint(None, 'messages', ['channel_id'])
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'conversation_id')
    op.drop_column('messages', 'read')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('messages', sa.Column('read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_index('ix_messages_status', table_name='messages')
    op.drop_index('ix_messages_session_created', table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('messages', 'status_updated_at')
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'message_type')
    op.drop_column('messages', 'channel_id')
    op.drop_column('messages', 'session_id')
    op.add_column('conversations', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    op.drop_column('conversations', 'channel')
    op.drop_index('ix_sessions_conversation_active', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
